name: Apache Atlas Docker Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: apache-atlas

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/Dockerfile.ubuntu
            image: ghcr.io/hritvikpatel4/apache-atlas
            tag: ubuntu-bionic
          - dockerfile: ./docker/Dockerfile.centos
            image: ghcr.io/hritvikpatel4/apache-atlas
            tag: centos7
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Setup log size to be 2 GiB
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=2147483648
        
      # - name: Log in to Docker Hub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the GitHub container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: hritvikpatel4
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: type=raw,value=${{ matrix.tag }}
          # images: |
          #   ntwine/${{ env.IMAGE_NAME }}
          #   ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
