name: Apache Atlas Docker Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: apache-atlas

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=1073741824
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ntwine/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
